---
# tasks file for remove-python2

- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Load tasks file with install tasks based on the OS type
  ansible.builtin.include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - remove_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - remove_{{ ansible_distribution }}.yml
        - remove_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"
